In [2]:
#####Causal graph modeling with Latent Decomposition#####
import numpy as np
import pandas as pd
import matplotlib.pyplot  as plt
import numpy.matlib
import scipy.linalg
import itertools
from scipy import sparse
from scipy.stats import norm
from pandas.tools.plotting import scatter_matrix
from numpy.random import *
from scipy import optimize

#np.random.seed(98537)

In [ ]:
##多項分布の乱数を生成する関数
def rmnom(pr, n, k, no, pattern):
    z_id = np.argmax((np.cumsum(pr, axis=1) >= np.random.uniform(0, 1, n)[:, np.newaxis]), axis=1)
    return z_id
    if pattern==1:
        Z = sparse.coo_matrix((np.repeat(1, n), (no, np.array(z_id))), shape=(n, k))   #スパース行列の設定
        return z_id, Z

In [4]:
####データの生成####
##データの設定
k11 = 12
k12 = 10
k2 = 10
hh = 5000
item = 3000
element = 300


Lambda = np.random.gamma(30.0, 1/0.2, item)
pt = np.random.poisson(Lambda, item)
N = np.sum(pt)
k_vec1 = np.repeat(1.0, k1)
k_vec2 = np.repeat(1.0, k2)
k_vec3 = np.repeat(1.0, k3)

In [13]:
omega = np.random.normal(0, 0.3, k1*k1).reshape(k1, k1)
theta_u = np.random.normal(0, 0.5, k1) 
theta_v = np.random.normal(0, 0.5, k1)
theta_e = np.random.normal(1, 0.3, k1)

In [14]:
np.dot(theta_u * theta_v * theta_e, omega)

array([-0.18075862, -0.23827431,  0.16009925, -0.16843199,  0.00358193,
        0.29123849, -0.12535933,  0.40019751, -0.16613821,  0.03741341])

In [8]:
theta_v

array([ 0.83500058,  0.77317988,  0.27447334, -0.62295032,  0.66997671,
        0.43179294,  0.0531165 ,  0.53778709, -0.50359219,  0.48062951])

In [10]:
theta_e

array([0.71755566, 1.63093154, 0.68870099, 0.75173783, 1.07803485,
       0.84279954, 0.50315339, 0.88054018, 1.1002531 , 1.50519123])